id: I55E4BFEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:41:06+00:00'
last_modified: '2022-06-08T16:26:53.623735+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14503
  title: གྲོང་སྡེ་རིམ་པའི་གད་སྙིགས་དོ་དམ་བྱེད་ཐབས་སྐོར་གྱི་ལག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '2452':
      image_group_id: I1KG15858
      title: ''
      total_pages: 112
      order: 1
      base_file: 2452.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
